### ISSUE TITLE
Issue using spire with spark

### ISSUE THREAD

**Issue by NoamShaish** [typelevel/spire#849]
***Description:***
I am not sure it is spire issue and not spark issue but I hope I could get help here.
I am experiencing a strange behaviour when trying to use spire-extras with spark.
For some reason ```IntervalTrie``` is failing to access ```math.Interval$fromBounds```
***Spire Version:*** 0.16.2  
***Spark version:*** 2.3.2
***Steps to reproduce:***
```bash
spark-shell --packages org.typelevel:spire-extras_2.11:0.16.2,org.typelevel:spire_2.11:0.16.2
```

```scala
import spire.math.extras.interval.IntervalTrie._
atOrAbove(3)
```

result:
```
java.lang.NoSuchMethodError: spire.math.Interval$.fromBounds(Lspire/math/interval/Bound;Lspire/math/interval/Bound;Lcats/kernel/Order;)Lspire/math/Interval;
  at spire.math.extras.interval.IntervalTrie$.spire$math$extras$interval$IntervalTrie$$foreachInterval(IntervalTrie.scala:278)
  at spire.math.extras.interval.IntervalTrie$IntervalTrieImpl$$anon$1.foreach(IntervalTrie.scala:474)
  at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
  at spire.math.extras.interval.IntervalTrie$IntervalTrieImpl$$anon$1.map(IntervalTrie.scala:471)
  at spire.math.extras.interval.IntervalTrie$IntervalTrieImpl.toString(IntervalTrie.scala:497)
  at scala.runtime.ScalaRunTime$.scala$runtime$ScalaRunTime$$inner$1(ScalaRunTime.scala:332)
  at scala.runtime.ScalaRunTime$.stringOf(ScalaRunTime.scala:337)
  at scala.runtime.ScalaRunTime$.replStringOf(ScalaRunTime.scala:345)
  at .$print$lzycompute(<console>:10)
  at .$print(<console>:6)
  at $print(<console>)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:786)
  at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1047)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)
  at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
  at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
  at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:637)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:569)
  at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
  at scala.tools.nsc.interpreter.ILoop.interpretStartingWith(ILoop.scala:807)
  at scala.tools.nsc.interpreter.ILoop.command(ILoop.scala:681)
  at scala.tools.nsc.interpreter.ILoop.processLine(ILoop.scala:395)
  at scala.tools.nsc.interpreter.ILoop.loop(ILoop.scala:415)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply$mcZ$sp(ILoop.scala:923)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
  at scala.tools.nsc.interpreter.ILoop$$anonfun$process$1.apply(ILoop.scala:909)
  at scala.reflect.internal.util.ScalaClassLoader$.savingContextLoader(ScalaClassLoader.scala:97)
  at scala.tools.nsc.interpreter.ILoop.process(ILoop.scala:909)
  at org.apache.spark.repl.Main$.doMain(Main.scala:76)
  at org.apache.spark.repl.Main$.main(Main.scala:56)
  at org.apache.spark.repl.Main.main(Main.scala)
  at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  at java.lang.reflect.Method.invoke(Method.java:498)
  at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
  at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:894)
  at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:198)
  at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:228)
  at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:137)
  at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

```scala
import cats.kernel.instances.int._
import spire.math.interval._
import spire.math.Interval
Interval.fromBounds(Closed(3), Unbound())
```

result:
```
java.lang.NoSuchMethodError: spire.math.Interval$.fromBounds(Lspire/math/interval/Bound;Lspire/math/interval/Bound;Lcats/kernel/Order;)Lspire/math/Interval;
  ... 55 elided
```

**Comment by denisrosset** [comment]
Thanks for the nice minimal example . Are you sure Spark does not pull an earlier Spire dependency on its own? The method missing exception is often a sign of conflicting dependency versions.

**Comment by denisrosset** [comment]
I'm sorry, but Spire is a not yet at a 1.0 issue and there are no binary compatibility guarantees yet!

I suggest you stick with the Spire version that was bundled with Spark.

Closing this for now.
